### ISSUE TITLE
Cropped Image filename

### ISSUE THREAD

**Issue by womackj1** [gapmiss/croppie-for-obsidian#1]
When I crop an image, an 8 character string is appended to the end of the filename.
For example, when cropping an image `example-image`, the cropped image is saved as `example-image-mQAC1DqF`.

Since there is already an option to output cropped images to a different folder, I think removing this string would improve the user experience. 

I'm a fan of the plugin!

**Comment by gapmiss** [comment]
@womackj1 I've added a new setting to toggle on/off the file appending random ID.

**Comment by gapmiss** [comment]
New version found here: https://github.com/gapmiss/croppie-for-obsidian/releases/tag/0.2.0-beta
